# fly.toml app configuration file generated for portfolio-withered-frost-6996 on 2025-05-31T10:54:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-withered-frost-6996'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
